spring.application.name=battleship

#Database properties
spring.datasource.url = jdbc:postgresql://x.x.x.x:xxxx/battleship
spring.datasource.username =
spring.datasource.password =

#Security properties
security.initialAdminPassword=