spring.application.name=battleship

#Database properties
spring.datasource.url = jdbc:postgresql://localhost:5432/battleship
spring.datasource.username =user123
spring.datasource.password =user123

#Security properties
security.initialAdminPassword=Test123456!